-- MySQL Script generated by MySQL Workbench
-- Sun Apr 26 18:47:45 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema register
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema register
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `register` DEFAULT CHARACTER SET utf8 ;
USE `register` ;

-- -----------------------------------------------------
-- Table `register`.`person`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `register`.`person` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(145) NULL,
  `birthdate` DATE NULL,
  `occupation` VARCHAR(145) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `register`.`projects`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `register`.`projects` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(145) NULL,
  `person_id` INT NOT NULL,
  `occupation_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_projects_person_idx` (`person_id` ASC) VISIBLE,
  INDEX `fk_projects_person1_idx` (`occupation_id` ASC) VISIBLE,
  CONSTRAINT `fk_projects_person`
    FOREIGN KEY (`person_id`)
    REFERENCES `register`.`person` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_projects_occupation`
    FOREIGN KEY (`occupation_id`)
    REFERENCES `register`.`person` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
